dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://${nacos.host}:${nacos.port}
#    address: zookeeper://${zookeeper.host}:${zookeeper.port}
  consumer:
    timeout: 60000

nacos:
  host: 192.168.39.233
  port: 8848

zookeeper:
  host: 192.168.39.233
  port: 2181