dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry: #注册中心
    address: nacos://${nacos.host}:${nacos.port}
  metadata-report: #将元数据信息（接口参数名字，类型）等注册到nacos
    address: nacos://${nacos.host}:${nacos.port}
  config-center: #配置中心
    address: nacos://${nacos.host}:${nacos.port}
  provider:
    filter: providerTraceFilter

nacos:
  host: 192.168.39.233
  port: 8848