dubbo:
  application:
    name: business-service
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://${nacos.host}:${nacos.port}
  metadata-report:
    address: nacos://${nacos.host}:${nacos.port}
  consumer:
    filter: consumerTraceFilter

nacos:
  host: 192.168.39.233
  port: 8848

spring:
  application:
    name: business-service

server:
  port: 8080